### ISSUE TITLE
No visual indication of selected item in pop-up lists in light mode

### ISSUE THREAD

**Issue by erikwestra** [santiyounger/Wasp-Obsidian-Theme#2]
Hi there,

First off, thanks for this great theme -- it's been my theme of choice since I started using Obsidian.

I prefer light mode, and Wasp is definitely the best of the light themes available, even though (as you say) you haven't optimised it for this mode yet.

One thing, though: with this theme, if you bring up a pop-up list, for example the link completion list by typing "[[", or the tag list by typing "#", Obsidian displays a list of items, and you can use the arrow keys etc to move the selection, and then press Return to select the highlighted item, but with Wasp in light mode, the highlighting isn't shown.

If I turn off the Wasp theme, even in light mode, the popup lists show the highlighted item in light gray, but with Wasp there's no highlighting at all.

Any chance you could fix this -- or perhaps give some clue as to how to re-enable this using custom CSS?

Thanks!

**Comment by santiyounger** [comment]
Thanks for this, I've been postponing this for a long time, since I almost never use light mode. But I'm aware that this was an issue. 

I just spent the last couple hours solving it. 

Results for light mode still aren't perfect, but this problem is now solved

Thanks a lot! 

Steps to update it from Obsidian:

Settings > Appearance > Community Themes > Browse > Searching "Wasp" > Use  > Override

Let me know if things are looking good for you!

**Comment by erikwestra** [comment]
Thanks, @santiyounger -- sorry I didn't see this until now (I was expecting Github to notify me, but it didn't).

Unfortunately updating the theme like you suggest makes no difference.  There's still no visual highlighting in lists in light mode.

Is there any way of making sure that the latest version has been installed?  I get pop-up messages saying "Fetching CSS", "You're now using the Wasp theme by Santi", etc -- but list items still aren't being highlighted as I arrow up and down.  I tried switching to dark mode and the highlighting shows up there, so it's only a problem in light mode.

Sorry to be a nuisance...if there's anything I can do to help track this down, please let me know.
