### ISSUE TITLE
README doesn't appear in Community Plugins listing

### ISSUE THREAD

**Issue by colintedford** [santiyounger/Wasp-Obsidian-Theme#4]
The Community Plugins repo thinks you didn't submit a README. Maybe because it's README.org instead of .md?

**Comment by colintedford** [comment]
Reverie has the same problem.

**Comment by Mukilan-Krishnakumar** [comment]
Can confirm that the issue still exists. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71809485/211133352-f07b3fe7-6c52-4119-bab8-a16998c74cc6.png">

**Comment by Nesnick** [comment]
I have this same issue. 
![Screenshot 2024-05-23 162341](https://github.com/santiyounger/Wasp-Obsidian-Theme/assets/48900277/d51a966b-7a75-4468-a34d-077e5e9f6b3b)

**Comment by amazebasics** [comment]
Hello. Is there any updates on this? I just started using Obsidian as well and would like to use this theme. A README would be a good thing to have to describe how this is different from the others. Thank you!

**Comment by Cubius** [comment]
the issue seems quite obvious, obsidian is looking for a `README.md` while the repo contains a `README.org`

seeing how the last commit was a minor change to said readme and dates back to January 2023 and the commit before that was in July of 2021, i think its fair to say this theme is abandoned

**Comment by amazebasics** [comment]
Is it possible to change it through a PR? Surely all the author has to do is approve it, right?

**Comment by santiyounger** [comment]
wow! so sorry guys for such a late reply, I can't believe I lost track of this for so long, my bad.

I just updated it from README.org to README.md

I can't see it taking effect in Obsidian themes yet, but it might just take a bit to show there.

Thanks again to everyone who insisted on this for so long, again, sorry it took me this long
